name: Task10_failure_handling

on: [workflow_dispatch]

jobs:
  sucessJob:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo "Step 1..."

  failureJob:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Step 2
        run: |
          echo "Step 2..."
      - name: FailureStep
        run: |
          exit 1
          