name: Task8_deploy_only_from_main_branch

on: [push]

jobs:
  prepare_env:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload source as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-source
          path: python-app/
  
  deploy:
    runs-on: ubuntu-slim
    needs: [prepare_env]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-source
          path: python-app

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python-app/requirements.txt

      - name: Deployment
        if: github.ref == 'refs/heads/development' && github.repository_owner == 'Ostry7'
        run: |
          echo "Deploy..."
