name: Task3_conditional_steps

on: [workflow_dispatch, push]

jobs:
  commit_contains_skip_tests:
    if: ${{ contains(github.event.head_commit.message, 'skip tests')}}
    runs-on: ubuntu-slim
    steps:
      - run: echo "Skipping tests due to commit message" 

